import numpy as np
import matplotlib.pyplot as plt


# --------------------------------------------------
# Configuration
# --------------------------------------------------

# Charges: (x position, y position, charge value in nano-Coulombs)
# charges = [
#     (-3, 0, -2),
#     (3, 0, 20)
# ]

charges = [
    (-3, 2, -10),  # Top-left, negative
    (3, 2, 10),    # Top-right, positive
    (-3, -2, 10),  # Bottom-left, positive
    (3, -2, -10)   # Bottom-right, negative
]

# Simulation area
X_MIN, X_MAX = -5, 5
Y_MIN, Y_MAX = -5, 5

# Grid resolution
RESOLUTION = 100

# Coulomb constant
K = 9e9


# --------------------------------------------------
# Electric field calculation
# --------------------------------------------------

def calculate_electric_field(charges):
    """
    Calculate electric field components Ex and Ey
    generated by point charges.

    Returns:
        X, Y : mesh grid coordinates
        Ex, Ey : electric field components
    """

    x = np.linspace(X_MIN, X_MAX, RESOLUTION)
    y = np.linspace(Y_MIN, Y_MAX, RESOLUTION)

    X, Y = np.meshgrid(x, y)

    Ex = np.zeros_like(X)
    Ey = np.zeros_like(Y)

    for charge_x, charge_y, charge_value in charges:

        # Convert nano-Coulombs to Coulombs
        q = charge_value * 1e-9

        dx = X - charge_x
        dy = Y - charge_y

        # Avoid division by zero
        distance = np.sqrt(dx**2 + dy**2)
        distance = np.maximum(distance, 1e-12)

        # Electric field magnitude
        E = K * q / distance**2

        # Components
        Ex += E * (dx / distance)
        Ey += E * (dy / distance)

    return X, Y, Ex, Ey


# --------------------------------------------------
# Visualization
# --------------------------------------------------

def plot_field(X, Y, Ex, Ey, charges):
    """
    Plot electric field streamlines and charges.
    """

    fig, ax = plt.subplots(figsize=(8, 8))

    ax.set_aspect("equal")

    # Draw electric field lines
    ax.streamplot(
        X,
        Y,
        Ex,
        Ey,
        density=1.5,
        linewidth=1,
        color="black"
    )


    # Draw charges
    for x, y, q in charges:

        color = "red" if q > 0 else "blue"

        ax.scatter(
            x,
            y,
            s=abs(q) * 80,
            color=color,
            edgecolors="black",
            zorder=3,
            label=f"{q} nC"
        )

        ax.text(
            x + 0.15,
            y + 0.15,
            f"{q} nC",
            fontsize=10
        )


    # Labels and formatting
    ax.set_title(
        "2D Electric Field Simulator",
        fontsize=14
    )

    ax.set_xlabel("X position")
    ax.set_ylabel("Y position")

    ax.grid(
        True,
        alpha=0.3
    )

    # Create the legend and store its reference
    leg = ax.legend()
    
    # Iterate through the legend items and force them to a standard size
    for handle in leg.legend_handles:
        handle.set_sizes([80]) # 80 is a standard, readable size

    plt.show()


# --------------------------------------------------
# Main
# --------------------------------------------------

if __name__ == "__main__":

    X, Y, Ex, Ey = calculate_electric_field(charges)

    plot_field(
        X,
        Y,
        Ex,
        Ey,
        charges
    )